ALTER TABLE public."Message"
  ADD COLUMN IF NOT EXISTS edited_at TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS deleted_by_customer BOOLEAN NOT NULL DEFAULT false;
